FROM ubuntu:22.04

WORKDIR /HottelTravel

ENV BOT_TOKEN=""

COPY ./ ./

RUN apt-get update && \
    apt-get install -y curl cmake build-essential python3-dev python3 python3-pip libboost-all-dev locales && \
    locale-gen en_US.UTF-8 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

RUN chmod +x clean_up.sh run_tg_bot.sh

RUN ./clean_up.sh

EXPOSE 8888

ENTRYPOINT ["sh", "-c", "./run_tg_bot.sh \"$BOT_TOKEN\""]
