cities = [
    'eg/cairo',
    'ma/marrakech',
    'za/durban',
    'za/johannesburg',
    'za/cape-town',
    'jp/tokyo',
    'ae/dubai',
    'tr/istanbul',
    'th/bangkok',
    'jp/osaka',
    'fr/paris',
    'gb/london',
    'de/berlin',
    'de/munich',
    'nl/amsterdam',
    'us/new-york',
    'us/orlando',
    'us/los-angeles',
    'mx/mexico-city',
    'us/atlanta',
    'au/sydney',
    'eg/alexandria',
    'ma/casablanca',
    'za/pretoria',
    'jp/kyoto',
    'ae/abu-dhabi',
    'tr/ankara',
    'th/phuket',
    'fr/nice',
    'gb/manchester',
    'de/hamburg',
    'nl/rotterdam',
    'us/chicago',
    'us/miami',
    'us/san-francisco',
    'mx/cancun',
    'au/melbourne',
    'eg/sharm-el-sheikh',
    'ma/rabat',
    'za/stellenbosch',
    'jp/sapporo',
    'ae/sharjah',
    'tr/izmir',
    'th/chiang-mai',
    'fr/marseille',
    'gb/birmingham',
    'de/frankfurt',
    'nl/the-hague',
    'us/washington-dc',
    'us/las-vegas',
    'us/seattle',
    'mx/guadalajara',
    'au/brisbane',
    'br/rio-de-janeiro',
    'br/sao-paulo',
    'in/mumbai',
    'in/new-delhi',
    'cn/beijing',
    'cn/shanghai',
    'ru/moscow',
    'ru/saint-petersburg',
    'kr/seoul',
    'kr/busan',
    'sg/singapore',
    'it/rome',
    'it/milan',
    'es/madrid',
    'es/barcelona',
    'ca/toronto',
    'ca/vancouver',
    'ca/montreal',
    'ar/buenos-aires',
    'cl/santiago',
    'co/bogota',
    'pe/lima',
    'cl/valparaiso',
    'ar/mendoza',
    'no/oslo',
    'se/stockholm',
    'dk/copenhagen',
    'fi/helsinki',
    'pl/warsaw',
    'cz/prague',
    'hu/budapest',
    'pt/lisbon',
    'pt/porto',
    'gr/athens',
    'cy/nicosia',
    'hr/zagreb',
    'bg/sofia',
    'ro/bucharest',
    'ua/kyiv',
    'rs/belgrade',
    'si/ljubljana',
    'sk/bratislava',
    'lt/vilnius',
    'lv/riga',
    'ee/tallinn',
    'is/reykjavik',
    'sa/riyadh',
    'sa/jeddah',
    'ir/tehran',
    'pk/karachi',
    'pk/lahore',
    'bd/dhaka',
    'lk/colombo',
    'mm/yangon',
    'kh/phnom-penh',
    'vn/hanoi',
    'vn/ho-chi-minh-city',
    'my/kuala-lumpur',
    'ph/manila',
    'id/jakarta',
    'id/bali',
    'nz/auckland',
    'nz/wellington',
    'fj/suva',
    'pg/port-moresby',
    'tw/taipei',
    'hk/hong-kong',
    'mo/macau',
    'bn/bandar-seri-begawan',
    'np/kathmandu',
    'bt/thimphu',
    'mv/male',
    'np/pokhara',
    'kr/jeju',
    'tw/kaohsiung',
    'jp/nagoya',
    'jp/hiroshima',
    'jp/fukuoka',
    'au/adelaide',
    'au/perth',
    'au/darwin',
    'nz/christchurch',
    'id/surabaya',
    'th/chiang-rai',
    'my/penang',
    'lk/galle',
    'bd/chittagong',
    'ph/cebu',
    'vn/da-nang',
    'mm/mandalay',
    'la/vientiane',
    'kh/siem-reap',
    'np/lumbini',
    'in/bangalore',
    'in/chennai',
    'in/hyderabad',
    'in/kolkata',
    'in/ahmedabad',
    'in/pune',
    'in/jaipur',
    'in/kochi',
    'in/udaipur',
    'in/goa',
    'lk/kandy',
    'pk/islamabad',
    'pk/faisalabad',
    'pk/rawalpindi',
    'af/kabul',
    'tj/dushanbe',
    'tm/ashgabat',
    'uz/tashkent',
    'kz/almaty',
    'kg/bishkek',
    'mn/ulaanbaatar',
    'ng/lagos',
    'za/johannesburg',
    'ke/nairobi',
    'gh/accra',
    'sn/dakar',
    'et/addis-ababa'
    'ug/kampala',
    'cm/douala',
    'zm/lusaka'
]
countries = {
    'belgium': 'brussels',
    'russia': 'moscow',
    'france': 'paris',
    'italy': 'rome',
    'spain': 'madrid',
    'germany': 'berlin',
    'united-kingdom': 'london',
    'japan': 'tokyo',
    'china': 'beijing',
    'canada': 'toronto',
    'united-states': 'new-york',
    'brazil': 'sao-paulo',
    'india': 'delhi',
    'australia': 'sydney',
    'south-africa': 'cape-town',
    'egypt': 'cairo',
    'argentina': 'buenos-aires',
    'mexico': 'mexico-city',
    'south-korea': 'seoul',
    'netherlands': 'amsterdam',
    'turkey': 'istanbul',
    'switzerland': 'zurich',
    'portugal': 'lisbon',
    'greece': 'athens',
    'thailand': 'bangkok',
    'sweden': 'stockholm',
    'norway': 'oslo',
    'denmark': 'copenhagen',
    'austria': 'vienna',
    'finland': 'helsinki',
    'ireland': 'dublin',
    'new-zealand': 'auckland',
    'poland': 'warsaw',
    'czech-republic': 'prague',
    'hungary': 'budapest',
    'indonesia': 'jakarta',
    'malaysia': 'kuala-lumpur',
    'singapore': 'singapore',
    'philippines': 'manila',
    'vietnam': 'hanoi',
    'pakistan': 'karachi',
    'bangladesh': 'dhaka',
    'nigeria': 'lagos',
    'colombia': 'bogota',
    'peru': 'lima',
    'chile': 'santiago',
    'venezuela': 'caracas',
    'saudi-arabia': 'riyadh',
    'uae': 'dubai',
    'iran': 'tehran',
    'israel': 'tel-aviv',
    'romania': 'bucharest',
    'belarus': 'minsk',
    'kazakhstan': 'almaty',
    'ukraine': 'kyiv',
    'morocco': 'marrakech',
    'algeria': 'algiers',
    'angola': 'luanda',
    'ethiopia': 'addis-ababa',
    'ghana': 'accra',
    'ivory-coast': 'abidjan',
    'kenya': 'nairobi',
    'tanzania': 'dar-es-salaam',
    'uganda': 'kampala',
    'zambia': 'lusaka',
    'zimbabwe': 'harare',
    'malawi': 'lilongwe',
    'mozambique': 'maputo',
    'sudan': 'khartoum',
    'tunisia': 'tunis',
    'sri-lanka': 'colombo',
    'nepal': 'kathmandu',
    'myanmar': 'yangon',
    'laos': 'vientiane',
    'cambodia': 'phnom-penh',
    'lebanon': 'beirut',
    'jordan': 'amman',
    'oman': 'muscat',
    'qatar': 'doha',
    'kuwait': 'kuwait-city',
    'bahrain': 'manama',
    'azerbaijan': 'baku',
    'georgia': 'tbilisi',
    'armenia': 'yerevan',
    'uzbekistan': 'tashkent',
    'turkmenistan': 'ashgabat',
    'tajikistan': 'dushanbe',
    'kyrgyzstan': 'bishkek',
    'afghanistan': 'kabul',
    'iraq': 'baghdad',
    'syria': 'damascus',
    'libya': 'tripoli',
    'yemen': 'sanaa',
    'north-korea': 'pyongyang',
    'mongolia': 'ulaanbaatar'
}
